### ISSUE TITLE
Fails with exception in WPF when using static/dynamic resource

### ISSUE THREAD

**Issue by DanyaSWorlD** [panthernet/XamlRadialProgressBar#1]
I have brush predefined in resource dictionary, which describes main app color, so, if i use it as foreground app fails with this error:
`System.Windows.Markup.XamlParseException: "Не удается зафиксировать этот объект Freezable."`

StackTrace:

System.Windows.Freezable.Freeze()
XamlRadialProgressBar.Arc.UpdateInternalBrushes()
XamlRadialProgressBar.Arc.UpdateFillBrush(System.Windows.DependencyObject, System.Windows.DependencyPropertyChangedEventArgs)
System.Windows.DependencyObject.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
System.Windows.FrameworkElement.OnPropertyChanged(System.Windows.DependencyPropertyChangedEventArgs)
System.Windows.DependencyObject.NotifyPropertyChange(System.Windows.DependencyPropertyChangedEventArgs)
System.Windows.DependencyObject.UpdateEffectiveValue(System.Windows.EntryIndex, System.Windows.DependencyProperty, System.Windows.PropertyMetadata, System.Windows.EffectiveValueEntry, ref System.Windows.EffectiveValueEntry, bool, bool, System.Windows.OperationType)
System.Windows.StyleHelper.ApplyTemplatedParentValue(System.Windows.DependencyObject, MS.Internal.FrameworkObject, int, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord>, System.Windows.DependencyProperty, System.Windows.FrameworkElementFactory)
System.Windows.StyleHelper.InvalidatePropertiesOnTemplateNode(System.Windows.DependencyObject, MS.Internal.FrameworkObject, int, ref MS.Utility.FrugalStructList<System.Windows.ChildRecord>, bool, System.Windows.FrameworkElementFactory)
System.Windows.FrameworkTemplate.InvalidatePropertiesOnTemplate(System.Windows.DependencyObject, object)

**Comment by panthernet** [comment]
Can't trace the exact reason as I don;t have a correct test case but I've updated the code to eliminate similar exceptions. Should be fixed.

**Comment by DanyaSWorlD** [comment]
Problem is gone. Thanks!
